name: Bypass auth
on: workflow_dispatch

jobs:
  bypass-auth-exe-echo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - run: |
          echo "github token"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
